version: '3'

volumes:
  postgres_data:

services:
  starlette:
    build:
      context: app
      dockerfile: Dockerfile
    env_file: .env
    image: starlette_local
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--reload" ]

  postgres:
    image: postgres:10.15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
